language: ruby
rvm:
 - "2.2.0"
 - rbx
# uncomment this line if your project needs to run something other than `rake`:

before_script:
  - mysql -e 'create database myapp_test;'

script: bundle exec rspec spec
